## 7.1 Sparse matrix의 개념과 Python에서의 사용

In [6]:
import numpy as np
import pandas as pd
# sparse matrix를 사용하기 위한 scipy library
from scipy.sparse import csr_matrix

# 간단한 테스트를 위한 임시 데이터
ratings = {'user_id' : [1,2,4],
           'movie_id' : [2,3,7],
           'rating' : [4,3,1],}
ratings = pd.DataFrame(ratings)

# Pandas pivot을 이용해서 full matrix 변환
# 일반적인 Datarame의 pivot 기능을 사용해서 full matrix 변환
rating_matrix = ratings.pivot(index = 'user_id',
                              columns='movie_id',
                              values='rating').fillna(0)
full_matrix = np.array(rating_matrix)
print(full_matrix)

[[4. 0. 0.]
 [0. 3. 0.]
 [0. 0. 1.]]


In [12]:
# Sparse matrix를 이용해서 full matrix 변환
# 원소의 값(평점) 지정
data = np.array(ratings['rating'])
# row 인덱스 지정
row_indices = np.array(ratings['user_id'])
# column 인덱스 지정
col_indices = np.array(ratings['movie_id'])
# 원래 데이터를 csr_matrix로 변환
rating_matrix = csr_matrix((data,(row_indices,col_indices)), dtype = int)
print(rating_matrix)

  (1, 2)	4
  (2, 3)	3
  (4, 7)	1


In [23]:
print(rating_matrix[1,2])
print(rating_matrix[2,3])
print(rating_matrix[4,7])

4
3
1


In [25]:
full_matrix2 = rating_matrix.toarray()
print(full_matrix2)

[[0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]]
